### ISSUE TITLE
Values go into negatives when printing list sorted by value

### ISSUE THREAD

**Issue by W4LLST0NE** [htach/roliwrapper#2]
When printing a list of items sorted by value, some of them go into the negative.

Input:
`print(items.sort_by('value'))`

Output:
`(more output) ...Item(Id=10467162863, Name='XXL Basketball Head', Acronym='', Rap=2747, Value=-1, Default_Value=2747, Demand='None', Trend='None', Projected=False, Hyped=False, Rare=False), Item(Id=10467173753, Name='Guardian Angel Wings', Acronym='', Rap=1067, Value=-1, Default_Value=1067, Demand='None', Trend='None', Projected=False, Hyped=False, Rare=False), Item(Id=10467314620, Name='Black Headphones', Acronym='', Rap=1060, Value=-1, Default_Value=1060, Demand='None', Trend='None', Projected=False, Hyped=False, Rare=False), Item(Id=10467322128, Name='Gold Headphones', Acronym='', Rap=572, Value=-1, Default_Value=572, Demand='None', Trend='None', Projected=False, Hyped=False, Rare=False), Item(Id=10487204569, Name='NARS Lip Crossbody Bag 1.0', Acronym='', Rap=9388, Value=-1, Default_Value=9388, Demand='None', Trend='None', Projected=False, Hyped=False, Rare=False), Item(Id=10487228860, Name='NARS Lip Crossbody Bag 3.0', Acronym='', Rap=10385, Value=-1, Default_Value=10385, Demand='None', Trend='None', Projected=True, Hyped=False, Rare=False), Item(Id=10537487639, Name='NARS Light Reflecting Leather Moto Jacket', Acronym='', Rap=377, Value=-1, Default_Value=377, Demand='None', Trend='None', Projected=False, Hyped=False, Rare=False)]`

**Comment by htach** [comment]
hi there, it's meant to have a negative value as that means it's unvalued

**Comment by W4LLST0NE** [comment]
alr ty
